### PR TITLE
Added stopCharging support

### PR DESCRIPTION
**Pull request by SwedishNinja**
Sets the energy_to_add to 1. This effectivly limits charging to 1W.

### CODE REVIEW

**Comment by SwedishNinja** [comment]
Same as before. Added the stopCharging function. But removed the part where it figured out how much was already added.  It just sets the energy_to_add to the smallest number possible, 1.

**Comment by jesserockz** [comment]
I was playing around with the Android app. It looks like it only changes the override timestamp when you switch between `start charging`, `smart charging` and `stop charging` and the wh_to_add is always set to the max for the current vehicle.

**Comment by jesserockz** [comment]
This was my data from `16 December 2019 21:03:51 UTC`

```
Charge now
{
	"override_time": 1576529031,
	"energy_at_plugin": 0,
	"energy_to_add": 12000,
	"device_id": "XXXX",
	"token": "XXXX",
	"cmd": "set_override",
	"account_token": "XXXX"
}


Smart
{
	"override_time": 1576544686,
	"energy_at_plugin": 0,
	"energy_to_add": 12000,
	"device_id": "XXXX",
	"token": "XXXX",
	"cmd": "set_override",
	"account_token": "XXXX"
}

Smart 1am
{
	"override_time": 1576544860,
	"energy_at_plugin": 0,
	"energy_to_add": 12000,
	"device_id": "XXXX",
	"token": "XXXX",
	"cmd": "set_override",
	"account_token": "XXXX"
}


Stop
{
	"override_time": 1608066316,
	"energy_at_plugin": 0,
	"energy_to_add": 12000,
	"device_id": "XXXX",
	"token": "XXXX",
	"cmd": "set_override",
	"account_token": "XXXX"
}
```

**Comment by SwedishNinja** [comment]
Really old and pretty useless as I can just set the amp limit to 0! 
Thanks for the project!

**Pull request closed without merging**
