### PR TITLE
Added stopCharging support.

### PR DESCRIPTION
**Pull request by SwedishNinja**
Based on the setOverride API. Simply sets the current amount of
added energy to the desired amount of added energy.

### CODE REVIEW

**Comment by SwedishNinja** [comment]
Added stop charging support. Merge if you want!

**Comment by jesserockz** [comment]
Thanks, I will try this out when I get a chance.

**Comment by SwedishNinja** [comment]
Thanks!
I just realized that my Stop code is more complicated than it needs to be. I'll make a change when I have time, but I will just set energy to add to 1 no matter what the current energy added is.

**Comment by SwedishNinja** [comment]
Closing this and making a new new pull request.

**Pull request closed without merging**
